#pragma once
// Generated by tools/generate_fixture_anchors.py from packaging/mirror-acquisition-placements.json,
// packaging/mirror-placement-lighting.json, packaging/mirror-fixture-compat.json and the core
// location audit. Do not edit by hand.
#include "MirrorFixtureAnchorPolicy.h"

#include <array>
#include <string_view>

namespace MirrorFixtureAnchorPolicy
{
	using namespace std::literals;
	inline constexpr std::array<Fixture, 11> kFixtures{
		Fixture{ "MOSBreezehomeDressingMirror"sv, 0xA00, 0xD34, 0xB00, 0xCA124, 0x3EE56, Mounting::kWall,
			Vec3{ -512.000000F, 64.000000F, 320.000000F }, 4.712389F, 249.000000F, 1.000000F,
			Vec3{ -426.222331F, 54.739999F, 385.346936F }, 1.570796F, 0.560000F, Vec3{ -426.222332F, -1.260001F, 442.546951F } },
		Fixture{ "MOSHoneysideDressingMirror"sv, 0xA01, 0xD35, 0xB01, 0x94EB3, 0x94EA2, Mounting::kWall,
			Vec3{ 256.000000F, 256.000000F, 64.000000F }, 3.141593F, 437.000000F, 1.000000F,
			Vec3{ 277.612641F, 354.739984F, 131.150000F }, 1.570797F, 0.560000F, Vec3{ 277.612600F, 298.739984F, 188.000000F } },
		Fixture{ "MOSVlindrelHallDressingMirror"sv, 0xA02, 0xD36, 0xB02, 0xDC5FB, 0x4406B, Mounting::kWall,
			Vec3{ -2080.000000F, 1632.000000F, 64.000000F }, 3.141593F, 412.000000F, 1.000000F,
			Vec3{ -2169.794123F, 1575.814489F, 270.000000F }, -0.785398F, 0.442000F, Vec3{ -2130.196137F, 1615.412462F, 317.133715F } },
		Fixture{ "MOSHjerimDressingMirror"sv, 0xA03, 0xD37, 0xB03, 0x81459, 0x7903E, Mounting::kWall,
			Vec3{ 2688.000000F, -704.000000F, 192.000000F }, 4.712389F, 256.000000F, 1.000000F,
			Vec3{ 2581.746931F, -653.670000F, 259.150000F }, 0.000000F, 0.560000F, Vec3{ 2637.746931F, -653.670001F, 315.999997F } },
		Fixture{ "MOSProudspireManorDressingMirror"sv, 0xA04, 0xD38, 0xB04, 0x5F10C, 0x5B395, Mounting::kWall,
			Vec3{ 288.000000F, -976.000000F, 288.000000F }, 3.141593F, 224.000000F, 1.000000F,
			Vec3{ 156.750066F, -1033.470956F, 360.850000F }, 0.000000F, 0.500000F, Vec3{ 212.750066F, -1033.470967F, 412.842203F } },
		Fixture{ "MOSSleepingGiantDressingMirror"sv, 0xA10, 0xD39, 0xB05, 0x600A1, 0x5ED83, Mounting::kWall,
			Vec3{ -896.000000F, 0.000000F, 0.000000F }, 0.000000F, 834.000000F, 1.000000F,
			Vec3{ -1153.300759F, -557.985512F, 64.000034F }, 6.283178F, 0.640000F, Vec3{ -1089.300759F, -557.985053F, 138.532983F } },
		Fixture{ "MOSBeeAndBarbDressingMirror"sv, 0xA11, 0xD3A, 0xB06, 0x98F63, 0x96FA3, Mounting::kWall,
			Vec3{ 0.000000F, 448.000000F, 320.000000F }, 0.000000F, 437.000000F, 1.000000F,
			Vec3{ 26.474728F, 546.400001F, 383.200012F }, 1.570796F, 0.600000F, Vec3{ 26.474728F, 490.400001F, 443.000000F } },
		Fixture{ "MOSBanneredMareDressingMirror"sv, 0xA12, 0xD3B, 0xB07, 0xCA0B1, 0x602D2, Mounting::kWall,
			Vec3{ -768.000000F, -512.000000F, 320.000000F }, 3.141593F, 249.000000F, 1.000000F,
			Vec3{ -760.101661F, -493.247090F, 400.546936F }, -0.029199F, 0.400000F, Vec3{ -716.120416F, -491.962512F, 445.435718F } },
		Fixture{ "MOSCandlehearthDressingMirror"sv, 0xA13, 0xD3C, 0xB08, 0x550A9, 0x7BA7A, Mounting::kWall,
			Vec3{ -288.000000F, -4032.000000F, 52.988533F }, 4.712389F, 266.000000F, 1.000000F,
			Vec3{ -298.390213F, -4008.000000F, 136.500000F }, -3.141593F, 0.500000F, Vec3{ -354.390213F, -4007.999999F, 187.999993F } },
		Fixture{ "MOSSilverBloodDressingMirror"sv, 0xA14, 0xD3D, 0xB09, 0x7A68E, 0x5F6E9, Mounting::kWall,
			Vec3{ -4352.000000F, -1215.999878F, 144.000000F }, 1.570796F, 412.000000F, 0.750000F,
			Vec3{ -4348.000000F, -1371.078838F, 237.194513F }, -1.570796F, 0.500000F, Vec3{ -4348.000000F, -1315.078838F, 288.490640F } },
		Fixture{ "MOSWinkingSkeeverDressingMirror"sv, 0xA15, 0xD3E, 0xB0A, 0x6268C, 0x60799, Mounting::kWall,
			Vec3{ 1440.000000F, -1552.000000F, 288.000000F }, 1.570796F, 272.000000F, 1.000000F,
			Vec3{ 1446.888428F, -1685.935488F, 357.000000F }, -1.570796F, 0.537000F, Vec3{ 1446.888428F, -1629.935488F, 412.000000F } }
	};
	// Out-of-the-box overhaul compatibility (modlist matrix, 2026-09-17).
	inline constexpr std::array<CompatRule, 16> kCompatRules{
		CompatRule{ 5, CompatKind::kEquivalentBase, "JK's Sleeping Giant Inn.esp"sv, 0x82A },
		CompatRule{ 0, CompatKind::kBlockerReference, "Distinct Interiors.esp"sv, 0x39AF5 },
		CompatRule{ 0, CompatKind::kBlockerReference, "Distinct Interiors.esp"sv, 0x39B00 },
		CompatRule{ 0, CompatKind::kBlockerPlugin, "HSPlayerHomes - Breezehome.esp"sv, 0x0 },
		CompatRule{ 0, CompatKind::kBlockerPlugin, "Eli_Breezehome.esp"sv, 0x0 },
		CompatRule{ 0, CompatKind::kBlockerPlugin, "iWill_ARavensBreezeHome.esp"sv, 0x0 },
		CompatRule{ 1, CompatKind::kBlockerPlugin, "HSPlayerHomes - Honeyside.esp"sv, 0x0 },
		CompatRule{ 2, CompatKind::kBlockerPlugin, "HSPlayerHomes - Vlindrel Hall.esp"sv, 0x0 },
		CompatRule{ 3, CompatKind::kBlockerPlugin, "HSPlayerHomes - Hjerim.esp"sv, 0x0 },
		CompatRule{ 4, CompatKind::kBlockerPlugin, "HSPlayerHomes - Proudspire Manor.esp"sv, 0x0 },
		CompatRule{ 5, CompatKind::kBlockerPlugin, "HSRiverwood - Sleeping Giant Inn.esp"sv, 0x0 },
		CompatRule{ 6, CompatKind::kBlockerPlugin, "HSRiften - The Bee and Barb.esp"sv, 0x0 },
		CompatRule{ 7, CompatKind::kBlockerPlugin, "HSWhiterun - The Bannered Mare.esp"sv, 0x0 },
		CompatRule{ 8, CompatKind::kBlockerPlugin, "HSWindhelm - Candlehearth Hall.esp"sv, 0x0 },
		CompatRule{ 9, CompatKind::kBlockerPlugin, "HSMarkarth - Silver-Blood Inn.esp"sv, 0x0 },
		CompatRule{ 10, CompatKind::kBlockerPlugin, "HSSolitude - The Winking Skeever.esp"sv, 0x0 }
	};
}
