// Generated by tools/generate_mirror_feature_defaults.py; edit the package policy.
#pragma once
#include <array>
#include <string_view>

namespace MirrorFeatureDefaults
{
enum class Runtime { Other, SE, AE, VR };
inline constexpr char kProfileStamp[] = "MOS_INTERNAL_FEATURES_V1:04E90AAFC8B25422933A3ABE1F61B1321CBF4EB2B708A87388B4A7D4DB2B23C7";
inline constexpr std::array<std::wstring_view, 36> kFlat{
    L"MirrorsOfSkyrim_AELightingMaskTest.enable",
    L"MirrorsOfSkyrim_CasterDepthShaders.enable",
    L"MirrorsOfSkyrim_CoplanarPaneDepth.enable",
    L"MirrorsOfSkyrim_ENBScreenMask.enable",
    L"MirrorsOfSkyrim_ENBSunShadows.enable",
    L"MirrorsOfSkyrim_ENBSurfaceLights.enable",
    L"MirrorsOfSkyrim_HandAlphaTest.enable",
    L"MirrorsOfSkyrim_HandFaceCenter.enable",
    L"MirrorsOfSkyrim_HandMirrorHeadClearance.enable",
    L"MirrorsOfSkyrim_HandMirrorStandaloneSE.enable",
    L"MirrorsOfSkyrim_HandPortraitClipPlane.enable",
    L"MirrorsOfSkyrim_MirrorDrawAlphaTest.enable",
    L"MirrorsOfSkyrim_OcclusionCulling.enable",
    L"MirrorsOfSkyrim_PrivateSunShadows.enable",
    L"MirrorsOfSkyrim_RenderDistance.enable",
    L"MirrorsOfSkyrim_ScenePruning.enable",
    L"MirrorsOfSkyrim_ShadowAlphaTest.enable",
    L"MirrorsOfSkyrim_ShadowControls.enable",
    L"MirrorsOfSkyrim_ShadowMask.enable",
    L"MirrorsOfSkyrim_SurfaceLights.enable",
    L"RealisticReflections_HandMirrorBodyFraming.enable",
    L"RealisticReflections_HandMirrorLivePose.enable",
    L"RealisticReflections_HandMirrorLoweredResolution.enable",
    L"RealisticReflections_HandMirrorStablePortrait.enable",
    L"RealisticReflections_HandMirrorUnifiedActors.enable",
    L"RealisticReflections_M3MirrorSupplementalWorldRoot.enable",
    L"RealisticReflections_MirrorFleet.enable",
    L"RealisticReflections_MirrorMainViewLightGuard.enable",
    L"RealisticReflections_MirrorPaneCamera.enable",
    L"RealisticReflections_MirrorReplayRosterFilter.enable",
    L"RealisticReflections_MirrorSceneCoverage.enable",
    L"RealisticReflections_MirrorSkyCamera.enable",
    L"RealisticReflections_MultiMirror.enable",
    L"RealisticReflections_MultiMirrorEveryFrame.enable",
    L"RealisticReflections_NativeLightOwnership.enable",
    L"RealisticReflections_NifMirrors.enable",
};
inline constexpr std::array<std::wstring_view, 6> kVR{
    L"RealisticReflections_MultiMirror.enable",
    L"RealisticReflections_MultiMirrorEveryFrame.enable",
    L"RealisticReflections_VRCameraLayoutFix.enable",
    L"RealisticReflections_VRHandMirrorRuntimeFix.enable",
    L"RealisticReflections_VRPresentationFix.enable",
    L"RealisticReflections_VRViewCohortFix.enable",
};

// Legacy names are internal identifiers now. No file is opened for these
// features; unknown diagnostic opt-ins retain their separate legacy readers.
constexpr bool Enabled(Runtime runtime, std::wstring_view path) noexcept
{
    const auto separator = path.find_last_of(L"\\/");
    const auto name = separator == std::wstring_view::npos ? path : path.substr(separator+1);
    if (runtime == Runtime::SE || runtime == Runtime::AE) {
        for (const auto feature : kFlat) if (feature == name) return true;
    } else if (runtime == Runtime::VR) {
        for (const auto feature : kVR) if (feature == name) return true;
    }
    return false;
}
}
