#include "PCH.h"
#include "MirrorFleetRuntime.h"
#include "MirrorGpuTimer.h"
#include "MirrorPresentTiming.h"
#include "MirrorPerformance.h"
#include "MirrorPrivateShadow.h"
#include "HandMirrorSafetySettings.h"
#include "MirrorAdaptiveQuality.h"
#include "MirrorCaptureSizing.h"
#include "MirrorQualityPreset.h"
#include "HandMirrorPhysicalClipDepth.h"

namespace MirrorFleetRuntime
{
	namespace
	{
		std::mutex mutex;
		MirrorFleetPolicy::Fleet fleet;
		MirrorFleetPolicy::FrameQuality frameQuality;
		GpuTimer timer;
		bool gpuFaulted{};
		std::uint64_t reportTime{}, reportSource{}, colourAllocations{}, depthAllocations{};
		PresentTiming<> presentTiming;
		using Present = HRESULT(STDMETHODCALLTYPE*)(IDXGISwapChain*, UINT, UINT);
		Present original{};
		bool hookAttempted{};
		std::atomic<IDXGISwapChain*> observedSwapChain{}; // identity only, never dereferenced
		std::atomic_bool presentHookInstalled{false};
		GpuTimer::Results previousGPU{};
		bool PhaseTimingEnabled() noexcept
		{
			static const bool enabled = HandMirrorSafetySettings::EmptyMarker(
				L"Data\\MirrorsOfSkyrim_PhaseTiming.enable");
			return enabled || MirrorPerformance::DetailedTimingEnabled();
		}

		// Automatic quality. One observation per engine source frame (BeginFrame
		// runs once per rendered frame; frames generated by CS frame generation
		// only pass through Present), so the controller measures real game frame
		// time. They write MirrorFleetPolicy::adaptiveResolution and
		// adaptiveRefreshHz only; distances, shadows and the stored manual values
		// are untouched. Resolution and rate move through one owner-chosen ladder.
		std::atomic<std::uint64_t> publications{};
		MirrorAdaptiveQuality::Controller adaptive;
		unsigned adaptiveConfig{}, adaptiveApplied{ ~0u };
		std::uint64_t adaptiveSource{};
		bool adaptiveSuspendedLogged{};
		std::atomic<std::uint32_t> outputWidth{}, outputHeight{}, displayHz{};
		std::atomic<std::uint64_t> outputCheck{};

		void ReadOutputExtent(unsigned& width, unsigned& height) noexcept
		{
			width = height = 0;
			__try {
				auto* window = RE::BSGraphics::Renderer::GetCurrentRenderWindow();
				auto* chain = window ? reinterpret_cast<IDXGISwapChain*>(window->swapChain) : nullptr;
				DXGI_SWAP_CHAIN_DESC description{};
				if (chain && SUCCEEDED(chain->GetDesc(&description))) {
					width = description.BufferDesc.Width;
					height = description.BufferDesc.Height;
				}
			} __except (EXCEPTION_EXECUTE_HANDLER) { width = height = 0; }
		}

		// The monitor the game window is on, at its current mode; 0 when unknown.
		unsigned ReadDisplayHz() noexcept
		{
			HWND handle = nullptr;
			__try {
				auto* window = RE::BSGraphics::Renderer::GetCurrentRenderWindow();
				handle = window ? reinterpret_cast<HWND>(window->hWnd) : nullptr;
			} __except (EXCEPTION_EXECUTE_HANDLER) { handle = nullptr; }
			const HMONITOR monitor = handle ? MonitorFromWindow(handle, MONITOR_DEFAULTTONEAREST) : nullptr;
			MONITORINFOEXW info{};
			info.cbSize = sizeof(info);
			if (!monitor || !GetMonitorInfoW(monitor, &info)) return 0;
			DEVMODEW mode{};
			mode.dmSize = sizeof(mode);
			if (!EnumDisplaySettingsW(info.szDevice, ENUM_CURRENT_SETTINGS, &mode)) return 0;
			// 0 and 1 mean "hardware default".
			return mode.dmDisplayFrequency > 1 ? mode.dmDisplayFrequency : 0;
		}

		void RefreshOutput(std::uint64_t now) noexcept
		{
			const auto checked = outputCheck.load(std::memory_order_relaxed);
			if (checked && now - checked < 2'000'000) return;
			outputCheck.store(now, std::memory_order_relaxed);
			unsigned width{}, height{};
			ReadOutputExtent(width, height);
			outputWidth.store(width, std::memory_order_relaxed);
			outputHeight.store(height, std::memory_order_relaxed);
			displayHz.store(ReadDisplayHz(), std::memory_order_relaxed);
		}

		void ObserveAdaptiveQuality(std::uint64_t source, std::uint64_t now) noexcept
		{
			RefreshOutput(now);
			const bool framebuffer = MirrorCaptureSizing::UsesFramebuffer();
			if (!MirrorQualityPreset::Adaptive()) {
				// Manual/Preset own resolution and update rate.
				const bool had = MirrorFleetPolicy::adaptiveResolution.exchange(0, std::memory_order_relaxed) != 0;
				if (MirrorFleetPolicy::adaptiveRefreshHz.exchange(0, std::memory_order_relaxed) || had)
					logger::info("[MOS][AdaptiveQuality] suspended mode={}", static_cast<unsigned>(MirrorQualityPreset::CurrentMode()));
				adaptiveConfig = 0;
				adaptiveSuspendedLogged = false;
				return;
			}
			if (source == adaptiveSource) return;
			adaptiveSource = source;
			bool active{};
			{
				std::scoped_lock lock(mutex);
				active = frameQuality.visibleMirrors > 0;
			}
			// ENB's existing framebuffer contract still owns capture dimensions.
			// Its cadence is bounded by the same 60/30 steps; report the limitation.
			if (framebuffer != adaptiveSuspendedLogged) {
				adaptiveSuspendedLogged = framebuffer;
				adaptiveApplied = ~0u;
				logger::info("[MOS][AdaptiveQuality] resolutionFollowsFramebuffer={}", framebuffer);
			}
			const auto target = MirrorAdaptiveQuality::TargetFPS(MirrorQualityPreset::targetFPS.load(std::memory_order_relaxed));
			if (target != adaptiveConfig) {
				adaptive.Reset(target);
				adaptiveConfig = target;
				adaptiveApplied = ~0u;
				logger::info("[MOS][AdaptiveQuality] armed target={} FPS; ordered 2048/60 -> 1024/60 -> 1024/30 -> 512/30", target);
			}
			const auto level = adaptive.Observe(static_cast<double>(now) / 1000.0, active,
				publications.load(std::memory_order_relaxed));
			if (level != adaptiveApplied) {
				adaptiveApplied = level;
				const int chosen = MirrorAdaptiveQuality::ResolutionAt(level);
				const int refresh = MirrorAdaptiveQuality::RefreshAt(level);
				MirrorFleetPolicy::adaptiveResolution.store(framebuffer ? 0 : chosen, std::memory_order_relaxed);
				MirrorFleetPolicy::adaptiveRefreshHz.store(refresh, std::memory_order_relaxed);
				logger::info("[MOS][AdaptiveQuality] resolutionLimit={} refreshHz={} level={} target={} FPS resolutionFollowsFramebuffer={}",
					chosen, refresh, level, target, framebuffer);
			}
		}

		HRESULT STDMETHODCALLTYPE PresentThunk(IDXGISwapChain* chain, UINT sync, UINT flags)
		{
			static thread_local bool inside = false;
			if (inside || chain != observedSwapChain.load(std::memory_order_acquire) || (flags & DXGI_PRESENT_TEST))
				return original(chain, sync, flags);
			inside = true;
			MirrorPerformance::BeforePresent(chain);
			const auto now = Now();
			const auto result = original(chain, sync, flags);
			{
				std::scoped_lock lock(mutex);
				// Occluded/failed presents and the interval across them are not rendered frames.
				presentTiming.Observe(now, result == S_OK);
			}
			MirrorPerformance::AfterPresent(result == S_OK, Now());
			inside = false;
			return result;
		}

		void TryPresentHook() noexcept
		{
			if (hookAttempted) return;
			bool transactionActive = false;
			__try {
				auto* window = RE::BSGraphics::Renderer::GetCurrentRenderWindow();
				auto* chain = window ? reinterpret_cast<IDXGISwapChain*>(window->swapChain) : nullptr;
				if (!chain) return;
				hookAttempted = true;
				void** table = *reinterpret_cast<void***>(chain);
				MEMORY_BASIC_INFORMATION memory{};
				if (!table || !table[8] || !VirtualQuery(table[8], &memory, sizeof(memory)) ||
					memory.State != MEM_COMMIT || (memory.Protect & (PAGE_GUARD | PAGE_NOACCESS)) ||
					!(memory.Protect & (PAGE_EXECUTE | PAGE_EXECUTE_READ | PAGE_EXECUTE_READWRITE | PAGE_EXECUTE_WRITECOPY))) return;
				original = reinterpret_cast<Present>(table[8]);
				if (DetourTransactionBegin() != NO_ERROR) { original = nullptr; return; }
				transactionActive = true;
				if (DetourUpdateThread(GetCurrentThread()) != NO_ERROR ||
					DetourAttach(reinterpret_cast<PVOID*>(&original), reinterpret_cast<PVOID>(&PresentThunk)) != NO_ERROR) {
					DetourTransactionAbort(); transactionActive = false; original = nullptr; return;
				}
				const auto committed = DetourTransactionCommit();
				transactionActive = false;
				if (committed != NO_ERROR) { original = nullptr; return; }
				observedSwapChain.store(chain, std::memory_order_release);
				presentHookInstalled.store(true, std::memory_order_release);
			} __except (EXCEPTION_EXECUTE_HANDLER) {
				if (transactionActive) DetourTransactionAbort();
				hookAttempted = true;
			}
		}
	}
	std::uint64_t Now() noexcept
	{
		return static_cast<std::uint64_t>(std::chrono::duration_cast<std::chrono::microseconds>(
			std::chrono::steady_clock::now().time_since_epoch()).count());
	}
	void PreparePresentHook() noexcept { TryPresentHook(); }
	bool OutputSize(std::uint32_t& width, std::uint32_t& height) noexcept
	{
		width = outputWidth.load(std::memory_order_relaxed);
		height = outputHeight.load(std::memory_order_relaxed);
		return width && height;
	}
	std::uint32_t DisplayHz() noexcept { return displayHz.load(std::memory_order_relaxed); }
	void Reconcile(std::span<const MultiMirrorPolicy::Identity> ids) noexcept
	{
		if (!MirrorFleetPolicy::enabled.load(std::memory_order_relaxed)) return;
		std::scoped_lock lock(mutex); (void)fleet.Reconcile(ids);
	}
	bool Request(MultiMirrorPolicy::Identity id, bool visible, std::uint64_t now) noexcept
	{
		if (!MirrorFleetPolicy::enabled.load(std::memory_order_relaxed)) return visible;
		std::scoped_lock lock(mutex); return fleet.Request(id, visible, now, MirrorFleetPolicy::EffectiveRefresh());
	}
	void Planned(MultiMirrorPolicy::Identity id, std::uint64_t now) noexcept
	{
		if (!MirrorFleetPolicy::enabled.load(std::memory_order_relaxed)) return;
		std::scoped_lock lock(mutex); fleet.Planned(id, now, MirrorFleetPolicy::EffectiveRefresh());
	}
	namespace
	{
		MirrorFleetPolicy::Clock g_handClock{};
		// One clock; a pose change switches the interval, which the clock treats as due.
		std::uint64_t HandInterval(bool raised) noexcept
		{
			return MirrorFleetPolicy::Interval((raised ? MirrorFleetPolicy::handRefreshHz :
				MirrorFleetPolicy::handLoweredRefreshHz).load());
		}
	}
	bool HandDue(std::uint64_t now, bool raised) noexcept
	{
		std::scoped_lock lock(mutex);
		return g_handClock.Due(now, HandInterval(raised));
	}
	void HandPlanned(std::uint64_t now, bool raised) noexcept
	{
		std::scoped_lock lock(mutex);
		g_handClock.Attempt(now, HandInterval(raised));
	}
	std::uint64_t AdmissionSequence(MultiMirrorPolicy::Identity id, std::uint64_t source) noexcept
	{
		std::scoped_lock lock(mutex); return fleet.AdmissionSequence(id, source);
	}
	void Result(MultiMirrorPolicy::Identity id, std::uint64_t source, bool attempted,
		bool success, const char* failure, std::uint64_t cpu, std::uint32_t width) noexcept
	{
		if (!MirrorFleetPolicy::enabled.load(std::memory_order_relaxed)) return;
		if (success) publications.fetch_add(1, std::memory_order_relaxed);
		std::scoped_lock lock(mutex); fleet.Result(id, source, Now(), attempted, success, failure, cpu, width);
	}
	void Expired(MultiMirrorPolicy::Identity id, std::uint64_t capture) noexcept
	{
		if (!MirrorFleetPolicy::enabled.load(std::memory_order_relaxed)) return;
		std::scoped_lock lock(mutex); fleet.Expired(id, capture);
	}
	void BeginFrame(ID3D11Device*, ID3D11DeviceContext* context, std::uint64_t source) noexcept
	{
		MirrorPrivateShadow::ObserveSourceTime(source, Now());
		if (!MirrorFleetPolicy::enabled.load(std::memory_order_relaxed) && !MirrorPerformance::Requested()) return;
		TryPresentHook();
		ObserveAdaptiveQuality(source, Now());
		__try { if (!gpuFaulted) timer.Poll(context); }
		__except (EXCEPTION_EXECUTE_HANDLER) { gpuFaulted = true; }
	}
	bool ResumeImage(MultiMirrorPolicy::Identity id, std::uint64_t source,
		std::uint64_t captureSource, std::uint64_t capture) noexcept
	{
		if (!MirrorFleetPolicy::enabled.load(std::memory_order_relaxed)) return false;
		std::scoped_lock lock(mutex); return fleet.ResumeImage(id, source, captureSource, capture);
	}
	void BeginGPU(ID3D11Device* device, ID3D11DeviceContext* context) noexcept
	{
		__try {
			if (!gpuFaulted && MirrorFleetPolicy::enabled.load(std::memory_order_relaxed))
				(void)timer.Begin(device, context, PhaseTimingEnabled());
		} __except (EXCEPTION_EXECUTE_HANDLER) { gpuFaulted = true; }
	}
	void EndGPU(ID3D11DeviceContext* context) noexcept
	{
		__try {
			if (!gpuFaulted && MirrorFleetPolicy::enabled.load(std::memory_order_relaxed)) timer.End(context);
		} __except (EXCEPTION_EXECUTE_HANDLER) { gpuFaulted = true; }
	}
	PhaseToken BeginPhase(ID3D11DeviceContext* context, RenderPhase phase) noexcept
	{
		__try {
			if (!gpuFaulted && PhaseTimingEnabled()) return timer.BeginPhase(context, phase);
		} __except (EXCEPTION_EXECUTE_HANDLER) { gpuFaulted = true; }
		return 0;
	}
	void EndPhase(ID3D11DeviceContext* context, PhaseToken token) noexcept
	{
		__try { if (!gpuFaulted) timer.EndPhase(context, token); }
		__except (EXCEPTION_EXECUTE_HANDLER) { gpuFaulted = true; }
	}
	bool StandingGpu(double& totalMs, std::uint64_t& samples) noexcept
	{
		try {
			std::scoped_lock lock(mutex);
			const auto results = timer.Read();
			const auto& phase = results.phases[static_cast<std::size_t>(RenderPhase::kStanding)];
			totalMs = phase.totalMs;
			samples = phase.samples;
			return true;
		} catch (...) {
			return false;
		}
	}
	void Allocated(bool depth) noexcept { ++colourAllocations; depthAllocations += depth; }
	void SetFrameQuality(MirrorFleetPolicy::FrameQuality quality) noexcept
	{
		std::scoped_lock lock(mutex); frameQuality = quality;
	}
	void Report(std::uint64_t source, std::uint64_t bytes,
		const CapturePoolDiagnostics& targetPool) noexcept
	{
		if (!MirrorFleetPolicy::enabled.load(std::memory_order_relaxed)) return;
		const auto now = Now();
		if (!reportTime) {
			std::scoped_lock lock(mutex);
			reportTime = now; reportSource = source;
			(void)presentTiming.Take(); previousGPU = timer.Read();
			return;
		}
		if (now - reportTime < 5'000'000) return;
		try {
			std::scoped_lock lock(mutex);
			const double seconds = static_cast<double>(now - reportTime) / 1'000'000.0;
			const auto gpu = timer.Read();
			const auto count = gpu.samples - previousGPU.samples;
			const auto present = presentTiming.Take();
			logger::info("[MOS][Fleet] windowSeconds={:.3f} sourceFrames={} presentIntervals={} presentAvailable={} presentAvgMs={:.3f} presentMaxMs={:.3f} presentP50Ms={:.3f} presentP95Ms={:.3f} presentP99Ms={:.3f} gpuSamples={} gpuBatchAvgMs={:.3f} gpuInvalid={} gpuSaturated={} retained={} logicalBytes={} colorAllocations={} depthAllocations={} resolution={} refreshHz={} dynamicResolution={} visibleMirrors={} manualResolution={} presentPercentilesAvailable={} gpuFaulted={} gpuRejected={} windowEndUs={} adaptiveResolution={} adaptiveRefreshHz={} displayHz={}",
				seconds, source >= reportSource ? source - reportSource : 0, present.intervals, presentHookInstalled.load() && present.intervals != 0,
				present.average, present.maximum, present.p50, present.p95, present.p99, count,
				count ? (gpu.totalMs - previousGPU.totalMs) / count : 0.0, gpu.invalid, gpu.saturated,
				fleet.Entries().size(), bytes, colourAllocations, depthAllocations, frameQuality.resolution, MirrorFleetPolicy::refreshHz.load(),
				frameQuality.dynamic, frameQuality.visibleMirrors, frameQuality.manualResolution, present.percentilesAvailable, gpuFaulted, gpu.rejected, now, MirrorFleetPolicy::adaptiveResolution.load(),
				MirrorFleetPolicy::adaptiveRefreshHz.load(), displayHz.load(std::memory_order_relaxed));
			// Fixed-size counters are updated only on resize/reuse/eviction. Emit
			// changed shapes here, never log or allocate strings at texture creation.
			static CapturePoolDiagnostics previousPool{};
			for (std::size_t i = 0; i < targetPool.size(); ++i) {
				const auto& current = targetPool[i];
				const auto& before = previousPool[i];
				if (current == before) continue;
				logger::info("[MOS][TargetPool] size={}x{} allocations={} reuseHits={} evictions={} failures={} allocationTotalMs={:.3f} allocationLifetimeMaxMs={:.3f} windowAllocations={} windowAllocationMs={:.3f} windowEndUs={}",
					current.width, current.height, current.allocations, current.reuseHits, current.evictions,
					current.failures, current.allocationMicroseconds / 1000.0, current.maximumAllocationMicroseconds / 1000.0,
					current.allocations - before.allocations, (current.allocationMicroseconds - before.allocationMicroseconds) / 1000.0, now);
			}
			previousPool = targetPool;
			const auto depthStorage = HandMirrorPhysicalClipDepth::GetDiagnostics();
			logger::info("[MOS][DepthStorage] created={} storageReuses={} evictions={} residentBytes={} faults={} windowEndUs={}",
				depthStorage.resourceCreations, depthStorage.storageReuses, depthStorage.storageEvictions,
				depthStorage.storageBytes, depthStorage.faults, now);
			if (PhaseTimingEnabled()) {
				constexpr std::array names{"worldShadow", "playerShadow", "standing", "hand", "other"};
				for (std::size_t i = 0; i < names.size(); ++i) {
					const auto& current = gpu.phases[i]; const auto& before = previousGPU.phases[i];
					const auto samples = current.samples - before.samples;
					const auto cpuSamples = current.cpuSamples - before.cpuSamples;
					logger::info("[MOS][PhaseTiming] phase={} windowSeconds={:.3f} gpuSamples={} gpuTotalMs={:.3f} gpuAvgMs={:.3f} gpuInvalid={} cpuSamples={} cpuTotalMs={:.3f} cpuAvgMs={:.3f} rejected={} saturated={} queryPairs={} windowEndUs={}",
						names[i], seconds, samples, current.totalMs - before.totalMs,
						samples ? (current.totalMs - before.totalMs) / samples : 0.0, current.invalid,
						cpuSamples, current.cpuTotalMs - before.cpuTotalMs,
						cpuSamples ? (current.cpuTotalMs - before.cpuTotalMs) / cpuSamples : 0.0,
						gpu.phaseRejected, gpu.phaseSaturated, gpu.phaseQueryPairs, now);
				}
			}
			for (const auto& [id, e] : fleet.Entries()) {
				logger::info("[MOS][FleetRef] ref={:08X} generation={} visible={} planned={} attempts={} successes={} failures={} consecutiveFailures={} lastAttempt={} lastSuccess={} ageFrames={} firstFailure={} firstFailureSource={} lastFailure={} lastFailureSource={} retryDueUs={} cpuUs={} width={} resumePresentations={}",
					id, e.identity.generation, e.visible, e.planned, e.attempts, e.successes, e.failures, e.consecutiveFailures,
					e.lastAttemptSource, e.lastSuccessSource, e.lastSuccessSource && source >= e.lastSuccessSource ? source - e.lastSuccessSource : 0,
					e.firstFailure, e.firstFailureSource, e.lastFailure, e.lastFailureSource, e.clock.started && e.clock.next > now ? e.clock.next - now : 0, e.cpuMicroseconds, e.width, e.resumePresentations);
			}
			previousGPU = gpu; reportSource = source; reportTime = now;
		} catch (...) {}
	}
}
